name: Builder - Integration tests

on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/builder/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/builder/**'

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: cd ./cmd/builder && ./test/test.sh
