name: check-links
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'cmd/builder/**'
  pull_request:
    paths-ignore:
      - 'cmd/builder/**'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          base-branch: 'main'
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/check_links_config.json'
          check-modified-files-only: 'yes'
          folder-path: ''
